### ISSUE TITLE
更换conda作为python管理后插件无法运行

### ISSUE THREAD

**Issue by yixing312** [OrangeX4/vscode-typst-sympy-calculator#1]
我在更换conda后插件跑不起来了（当然也不排除我同期换了梯子的缘故），我在搜索和询问后无法解决问题，当前状态为我拉选部分公式开始计算时只会出现
![image](https://github.com/OrangeX4/vscode-typst-sympy-calculator/assets/96825143/acfbdc5c-4d0e-4c1a-a91f-01e25569b0f9)
这样的提示，在更换梯子后无果，我已经在环境中更新了需求的包
![image](https://github.com/OrangeX4/vscode-typst-sympy-calculator/assets/96825143/a5c460c3-d3a6-4517-9121-53dd3458c4b7)
![image](https://github.com/OrangeX4/vscode-typst-sympy-calculator/assets/96825143/190d761c-abf3-481f-8726-e5a3eeb463a8)
希望能够得到帮助！万分感谢！！

**Comment by OrangeX4** [comment]
请在插件设置将 Python 路径切换成你 conda 里面的 Python 路径



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月7日(周三) 上午10:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [OrangeX4/vscode-typst-sympy-calculator] 更换conda作为python管理后插件无法运行 (Issue #1)




 
我在更换conda后插件跑不起来了（当然也不排除我同期换了梯子的缘故），我在搜索和询问后无法解决问题，当前状态为我拉选部分公式开始计算时只会出现
 
 这样的提示，在更换梯子后无果，我已经在环境中更新了需求的包
 
 
 希望能够得到帮助！万分感谢！！

**Comment by yixing312** [comment]
已经通过在设置中添加该条命令的方式切换了路径，但是并没有起作用

从 Windows 版邮件发送

发件人: OrangeX4
发送时间: 2023年6月7日 11:13
收件人: OrangeX4/vscode-typst-sympy-calculator
抄送: yixing312; Author
主题: Re: [OrangeX4/vscode-typst-sympy-calculator] 更换conda作为python管理后插件无法运行 (Issue #1)

请在插件设置将 Python 路径切换成你 conda 里面的 Python 路径 



---原始邮件--- 
发件人: ***@***.***&gt; 
发送时间: 2023年6月7日(周三) 上午10:11 
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [OrangeX4/vscode-typst-sympy-calculator] 更换conda作为python管理后插件无法运行 (Issue #1) 





我在更换conda后插件跑不起来了（当然也不排除我同期换了梯子的缘故），我在搜索和询问后无法解决问题，当前状态为我拉选部分公式开始计算时只会出现 

这样的提示，在更换梯子后无果，我已经在环境中更新了需求的包 


希望能够得到帮助！万分感谢！！

**Comment by OrangeX4** [comment]
你现在使用的是 Typst Sympy Calculator 还是 Latex Sympy Calculator 呢？如果是前者的话，把 Latex Sympy Calculator 这个插件卸载后再试一下
