### ISSUE TITLE
Typst sympy calculator fails on package imports

### ISSUE THREAD

**Issue by sitandr** [OrangeX4/vscode-typst-sympy-calculator#2]
I really like that extension as it allows me to do math without moving from typing, but, unfortunately, it is barely usable since typst got basic package management.

For example, when I do `#import "@preview/physica:0.8.0"`, extension can't find file at `\@preview\physica:0.8.0`. That means I can't import _any_ packages if I want typst-calculator to work.

I understand that you don't work now on this package, but it should be very easy to fix (if you know where the importing is done).

Thank you for the cool extension anyway!

**Comment by OrangeX4** [comment]
Fixed it.

You could download the newest version by `pip install typst-sympy-calculator==0.6.1`.

Thanks for your issue :-)

**Comment by sitandr** [comment]
That was really fast, thanks a lot!

**Comment by DhruvDh** [comment]
I am facing a similar issue with imports.

When using the extension, all imports fail with this notification -

![Screenshot by Dropbox Capture](https://github.com/OrangeX4/vscode-typst-sympy-calculator/assets/14926467/07a8322d-a32b-426d-a05e-bdc9f352eec1)

The first letter of the import is always missing, no matter what the name of the file. Here, I tried running `@command:latex-sympy-calculator.numerical` on `sqrt(2)`, with the contents of `typst-sympy-calculator.typ` from [here](https://github.com/OrangeX4/typst-sympy-calculator.typ/blob/main/typst-sympy-calculator.typ).

```typ
#import "typst-sympy-calculator.typ": *

$ sqrt(2) $
```

**Comment by OrangeX4** [comment]
Do you have this file in the same directory?

**Comment by DhruvDh** [comment]
Yes, I do. The typst file compiles to a pdf as expected, it's just the extension is always complaining about an import with the first letter of the file name missing.

**Comment by OrangeX4** [comment]
Fixed it.

You could download the newest version by `pip install typst-sympy-calculator==0.6.2`.

Thanks!

**Comment by DhruvDh** [comment]
Thanks! I can confirm it works now!
