### ISSUE TITLE
Plublish on OpenVSX

### ISSUE THREAD

**Issue by liferooter** [OrangeX4/vscode-typst-sympy-calculator#3]
Please publish your great extension on [OpenVSX](https://open-vsx.org/) open-source and vendor-neutral alternative to Microsoft's Extension marketplace.

It would allow me to install your extension in my VSCodium :)

**Comment by OrangeX4** [comment]
Done :-)

https://open-vsx.org/extension/OrangeX4/vscode-typst-sympy-calculator
